language: node_js
node_js:
 - "node"
script:
  - ./node_modules/.bin/istanbul cover ./node_modules/.bin/_mocha frontend/src/*.js backend/src/*.js ./*.js -R spec
after_script:
  - ./node_modules/.bin/codeclimate-test-reporter < ./coverage/lcov.info
